#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs: https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
---
strategy: polling
no_screen_padding: "no"
dark_mode: "no"
static_data: ""
polling_verb: get
polling_url: "https://opentdb.com/api.php?amount=1&category={{category}}&difficulty={{difficulty}}"
polling_headers: ""
name: Open Trivia DB
refresh_interval: 15
custom_fields:
  - keyname: author_bio
    field_type: author_bio
    name: About This Plugin
    description: Shows Trivia Questions from Open Trivia DB
    github_url: https://github.com/who-would-know/trml-plugin-open-trivia-db
    learn_more_url: https://opentdb.com/
    email_address: whowouldknowdev@gmail.com

  - keyname: category
    field_type: select
    options:
      - General Knowledge: 9
      - Entertainment Books: 10
      - Entertainment Film: 11
      - Entertainment Music: 12
      - Entertainment Musicals & Theatres: 13
      - Entertainment Television: 14
      - Entertainment Video Games: 15
      - Entertainment Board Games: 16
      - Science & Nature: 17
      - Science Computers: 18
      - Science Mathematics: 19
      - Mythology: 20
      - Sports: 21
      - Geography: 22
      - History: 23
      - Politics: 24
      - Art: 25
      - Celebrities: 26
      - Animals: 27
      - Vehicles: 28
      - Entertainment Comics: 29
      - Science Gadgets: 30
      - Entertainment Japanese Anime & Manga: 3
    name: Trivia Category
    description: Optional - If no value is selected, will be random.
    optional: true

  - keyname: difficulty
    field_type: select
    name: Question Difficulty
    options:
      - Easy
      - Medium
      - Hard
    description: Optional - If no value is selected, will be random.
    optional: true
